development:
  adapter: postgresql
  encoding: unicode
  database: app_development
  username: <%= Rails.application.class.parent_name.to_s %>_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.application.class.parent_name.to_s %>_test
  username: edwardloveall
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.application.class.parent_name.to_s %>_production
  username: edwardloveall
  pool: 5
